Do not raise a TypeError exception if phone.data is None
Running the tests on the openSUSE build service to generate
packages fails because a TypeError exception is raised.

```
TypeError: object of type 'NoneType' has no len()
```

This commit checks that phone.data is not None before calling
len() in the two lines where the exception is raised.